### ISSUE TITLE
`range` function overshadowed by import in RDFClosure/OWLRL.py

### ISSUE THREAD

**Issue by wrobell** [RDFLib/OWL-RL#12]
The `range` is imported from `RDFClosure.RDFS` in `RDFClosure/OWLRL.py` module.

This import overshadows `range` function therefore processing for rules like `eq-diff2`, `eq-diff3` or `prp-adp` will crash an application.

**Comment by wrobell** [comment]
> > The range is imported from RDFClosure.RDFS in RDFClosure/OWLRL.py module.
> 
> > This import overshadows range function therefore processing for rules like eq-diff2, eq-diff3 or prp-adp will crash an application.
> 
> Yes, I ran into this issue last week, I know about it. I've written a fix for it on my working dev tree, but I haven't comitted it yet. I think it was caused by running python 2to3 on the code, the script changes all usages of `xrange` to `range` but it doesn't check if there already is a function called range in the code.

This sound like it. :) Please share your fix.
 
> > BTW. The readme file states this version passes the full batch of official OWL Full/RL tests. How to perform such test?
> 
> I don't know. My team only just took over the development/ownership of OWL-RL a couple of months ago, there is still a lot we don't know about the code, and testing is one of those things.

IMHO, it would be good to include the tests into the code. I have created ticket #14.

> Thank you for your contribution to this project. Can I just ask, what is your motivation for improving OWL-RL? What is your use case for this tool?

I want to revive the following project: https://gitlab.com/wrobell/uddo/. Such ontology would contain a lot of telemetry data (i.e. depth, temperature, etc). Therefore efficient handling of literals is quite important for me.

**Comment by ashleysommer** [comment]
@wrobell this was fixed in #17
