### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by bollwyvl** [RDFLib/OWL-RL#2]
I would love to use this, but the rest of my environment is python3.

Running 2to3 seems to do the trick, and could be supported as a package-time stuff:
https://pythonhosted.org/setuptools/python3.html

Would there be interest in supporting this?

**Comment by nicholascar** [comment]
A Python 3 branch has been created <https://github.com/RDFLib/OWL-RL/tree/py3> and this will soon be merged into master. It's working now but not fully tested yet. ETA early March, 2018.

**Comment by blokhin** [comment]
May I draw your attention to this Python interface to the `FaCT++` DL reasoner:
https://bitbucket.org/wrobell/coras
https://bitbucket.org/wrobell/factplusplus/src/factpp/factpp

**Comment by Danilka** [comment]
Any update on this? Would love to see this project revived!
