### ISSUE TITLE
Decide on better name for OWL-RL Python module and put the project on PyPI

### ISSUE THREAD

**Issue by wrobell** [RDFLib/OWL-RL#20]
The project name is OWL-RL, however the Python module name is `RDFClosure` (see also `setup.py`). Would be great to have better name, i.e. `owlrl` (if not taken).

Then please put the package on PyPI. :)

**Comment by ashleysommer** [comment]
Fixed by https://github.com/RDFLib/OWL-RL/commit/9a23615712e8e203c2942ecdd9a10671eb4fe27e
