### ISSUE TITLE
Use better name for closure.py script

### ISSUE THREAD

**Issue by wrobell** [RDFLib/OWL-RL#25]
According to PyPI description of the script, the script performs conversion. That would suggest `owlrl-convert` script. But it also performs OWL 2 RL inference. So what about simply `owlrl` or `owlrl-lint`?

**Comment by nicholascar** [comment]
I think we will go with the simplest owlrl. I'll see if we can make a renaming and documentation update today or tomorrow to fix this and a few more things.

**Comment by ashleysommer** [comment]
Fixed in https://github.com/RDFLib/OWL-RL/commit/29c4baf6ff91dd2135a5743098b09640c4c2905e
