### ISSUE TITLE
Include the updated license text in the source.

### ISSUE THREAD

**Issue by Aniket-Pradhan** [RDFLib/OWL-RL#37]
Hello Devs

I was packaging OWL-RL in the Fedora OS, and as per our guidelines, the source code should contain the full license text in it.

Furthermore, I checked out LICENSE.txt and it links to an older version of the W3C License. The license was renamed to "software and document" license in 2015 and can be found [here](https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document)
You can check out the disclaimer on the page the [current license links to](https://www.w3.org/Consortium/Legal/2002/copyright-software-20021231).

**Comment by Aniket-Pradhan** [comment]
The new license also says:

```
The full text of this NOTICE in a location viewable to users of the redistributed or derivative work.
```

So, I guess the full text should be included with the source

**Comment by iherman** [comment]
As the original author of the code and, therefore, the one who set this license: I have no objection setting it to the newer W3C license. However, I have handed over the maintenance of the code and the repo to others, ie, I would prefer to let them decide and do the changes...

**Comment by Aniket-Pradhan** [comment]
I have created a small PR updating the license with the new version and the full text.

> As the original author of the code and, therefore, the one who set this license: I have no objection setting it to the newer W3C license. However, I have handed over the maintenance of the code and the repo to others, ie, I would prefer to let them decide and do the changes...

I hope the new devs also find no objection with the change. Thanks! :smile:

**Comment by Aniket-Pradhan** [comment]
Hey there!

Bumping this ticket as it is blocking a package update in Fedora.
